helloworld.exe: main.cpp CapsuleRunner.h CapsuleRunner.cpp TimerThread.h TimerThread.cpp MessageHandler.h MessageHandler.tpp Message.h HelloWorld_Capsule.h HelloWorld_Capsule.cpp
	g++ main.cpp CapsuleRunner.cpp TimerThread.cpp HelloWorld_Capsule.cpp -std=c++20 -g -o helloworld.exe
clean:
	rm -f helloworld.exe