traddiclight.exe: main.cpp CapsuleRunner.h CapsuleRunner.cpp TimerThread.h TimerThread.cpp MessageHandler.h MessageHandler.tpp Message.h TrafficLight_Capsule.h TrafficLight_Capsule.cpp
	g++ main.cpp CapsuleRunner.cpp TimerThread.cpp TrafficLight_Capsule.cpp -std=c++20 -g -o trafficlight.exe
clean:
	rm -f trafficlight.exe