picomputer.exe: main.cpp CapsuleRunner.h CapsuleRunner.cpp MessageHandler.h MessageHandler.tpp Message.h PiComputer_Capsule.h PiComputer_Capsule.cpp Adder_Capsule.h Adder_Capsule.cpp Multiplier_Capsule.h Multiplier_Capsule.cpp
	g++ main.cpp CapsuleRunner.cpp PiComputer_Capsule.cpp Adder_Capsule.cpp Multiplier_Capsule.cpp -std=c++20 -g -o picomputer.exe
clean:
	rm -f picomputer.exe