pingpong.exe: main.cpp CapsuleRunner.h CapsuleRunner.cpp TimerThread.h TimerThread.cpp MessageHandler.h MessageHandler.tpp Message.h Ping_Capsule.h Ping_Capsule.cpp Pong_Capsule.h Pong_Capsule.cpp
	g++ main.cpp CapsuleRunner.cpp TimerThread.cpp Ping_Capsule.cpp Pong_Capsule.cpp -std=c++20 -g -o pingpong.exe
clean:
	rm -f pingpong.exe