helloTimer.exe: main.cpp CapsuleRunner.h CapsuleRunner.cpp TimerThread.h TimerThread.cpp MessageHandler.h MessageHandler.tpp Message.h HelloTimer_Capsule.h HelloTimer_Capsule.cpp
	g++ main.cpp CapsuleRunner.cpp TimerThread.cpp HelloTimer_Capsule.cpp -std=c++20 -g -o hellotimer.exe
clean:
	rm -f hellotimer.exe