main.exe: main.cpp CapsuleController.h CapsuleController.cpp TimerThread.h TimerThread.cpp MessageHandler.h MessageHandler.tpp Ping_Capsule.h Ping_Capsule.cpp Pong_Capsule.h Pong_Capsule.cpp CapsuleController.h CapsuleController.cpp Message.h
	g++ main.cpp CapsuleController.cpp TimerThread.cpp Ping_Capsule.cpp Pong_Capsule.cpp -std=c++20 -g -o main.exe
clean:
	rm -f main.exe