clock.exe: main.cpp Capsule.h CapsuleRunner.h CapsuleRunner.cpp TimerThread.h TimerThread.cpp MessageHandler.h MessageHandler.tpp Message.h Main_Capsule.h Main_Capsule.cpp Clock_Capsule.h Clock_Capsule.cpp Digit_Capsule.h Digit_Capsule.cpp
	g++ main.cpp CapsuleRunner.cpp TimerThread.cpp Main_Capsule.cpp Clock_Capsule.cpp Digit_Capsule.cpp -std=c++20 -g -o clock.exe
clean:
	rm -f clock.exe