main.exe: main.cpp CapsuleRunner.h CapsuleRunner.cpp MessageHandler.h MessageHandler.tpp Message.h Client_Capsule.h Client_Capsule.cpp Server_Capsule.h Server_Capsule.cpp
	g++ main.cpp CapsuleRunner.cpp Client_Capsule.cpp Server_Capsule.cpp -std=c++20 -g -o main.exe
clean:
	rm -f main.exe